server.port=8080
spring.application.name=AvengerScript IDE
spring.main.banner-mode=off
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
# Deshabilitar caché de estáticos para que los cambios carguen siempre frescos
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
